### PR TITLE
remove cost control from project creation

### PR DESCRIPTION
**Pull request by auhlig**
remove cost control from project creation workflow. please merge @majewsky @edda

### CODE REVIEW

**Comment by majewsky** [comment]
Did you test this?

**Comment by auhlig** [comment]
I tested project creation as domain admin and creating user project request.

**Comment by majewsky** [comment]
Okay then, let's see how this goes.

**Comment by auhlig** [comment]
Okay. Just in case: Don't hesitate to ping me on slack.

**Pull request merged**
