### PR TITLE
Resource management burst

### PR DESCRIPTION
**Pull request by majewsky**
grafik

grafik

grafik

### CODE REVIEW

**Comment by majewsky** [comment]
@reimannf This is good to go in from a technical perspective. Feel free to merge after having reviewed the wording.

**Comment by edda** [comment]
I'm trying to run this locally and get the following error when entering a project:

```
NoMethodError (undefined method `[]' for nil:NilClass):
plugins/resource_management/app/models/resource_management/project.rb:39:in `bursting_enabled'
```

Is there anything that needs to be configured manually somewhere? Like an environment variable or something.

**Comment by edda** [comment]
I have adjusted a few things in terms of styling/placement. Rest lgtm as far as I was able to check (don't have a project where the resource usage is actually bursting).

**Comment by majewsky** [comment]
@edda Looks good to us, except that this box is quite toned down (even though its CSS classes are `callout-emphasize`). Is that a bug?

grafik

**Comment by edda** [comment]
@majewsky Ah, sorry about that. I hadn't noticed because I didn't have a bursting project. Fixed it now.

**Pull request merged**
