### PR TITLE
[resmgmt] remove confusing dns records resource

### PR DESCRIPTION
**Pull request by Carthaca**
Hi @majewsky, can you have a look and clean up the db afterwards please?

### CODE REVIEW

**Comment by majewsky** [comment]
Looks good. Will merge tomorrow. (If not, please poke me.)

Do we need to do anything to reset the records quotas that we already wrote into Designate?

**Comment by Carthaca** [comment]
Good point, to avoid surprises setting the records-quota to our `20 * recordsets-quota` everywhere would be nice

**Comment by majewsky** [comment]
Ah, but that should be covered by a simple re-apply of the existing recordset quotas with the new driver. So no extra code needed.

**Comment by Carthaca** [comment]
Yes, you are planning to do that re-apply anyhow, right?

**Comment by majewsky** [comment]
I've added code to perform the reapply of the recordset quotas. (This cannot be done as a rake task or similar because I need the `services` object which is only accessible within controllers.)

**Pull request merged**
