### PR TITLE
servers: show sizing recommendation

### PR DESCRIPTION
**Pull request by hgw77**
image
image
image

### CODE REVIEW

**Comment by richardtief** [comment]
Looks good, thank you! However, one thing I find misleading is the phrase `vCPU was not found`. In this context it should rather be `vCPU Sizing is OK` or `vCPU is appropriate`.

**Comment by hgw77** [comment]
> 

Good Point, I will change that

**Comment by edda** [comment]
@richardtief Can this be rolled out from your side (i.e. are the metrics in place in the respective Prometheis)?

**Comment by richardtief** [comment]
Yes, the data is there. Let me make a few last minute changes to the query, then the whole thing can be sent.

**Comment by edda** [comment]
@richardtief Okay, cool. Please let me know when things are GO from your side.

**Review by edda — APPROVED** [review]

**Comment by richardtief** [comment]
@edda I had no more changes from my side after all, thank you. This can be shipped.

**Pull request merged**
